# Site name and description
name: BlockchainDame
description: Daily crypto news, blockchain insights, and market updates.

# Avatar or logo
avatar: https://raw.githubusercontent.com/gabelossless/blockchaindame/main/assets/logo.png
# (You can replace this URL with your own logo later)

# Footer links (socials)
footer-links:
  github: gabelossless
  twitter: BlockchainDame
  linkedin: gabelossless
  youtube: BlockchainDameChannel
  rss: feed.xml

# Enable commenting (optional)
disqus:

# Google Analytics tracking code (optional)
google_analytics:

# Site URL and base
url: https://gabelossless.github.io/blockchaindame
baseurl: ""

# Permalink structure
permalink: /:categories/:title/

# Jekyll Now release version
version: v1.2.0

# Markdown and syntax highlighting
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# Sass style
sass:
  style: :expanded

# Jekyll plugins
gems:
  - jekyll-sitemap
  - jekyll-feed

# Exclude unnecessary files from production
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
